package com.property_insurance.car_accident_claim_process;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Claim")
public class Claim implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.math.BigInteger id;
	private java.math.BigInteger memberId;

	private java.lang.String location;

	private java.time.LocalTime timeOfDay;

	private java.lang.String weatherConditions;

	private java.util.List<com.property_insurance.car_accident_claim_process.PersonInvolved> personInvolved;

	private java.util.List<com.property_insurance.car_accident_claim_process.PoliceOfficer> policeOfficer;

	private java.time.OffsetDateTime filingDate;

	private java.time.OffsetDateTime accidentDate;

	public Claim() {
	}

	public java.math.BigInteger getId() {
		return this.id;
	}

	public void setId(java.math.BigInteger id) {
		this.id = id;
	}

	public java.math.BigInteger getMemberId() {
		return this.memberId;
	}

	public void setMemberId(java.math.BigInteger memberId) {
		this.memberId = memberId;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.time.LocalTime getTimeOfDay() {
		return this.timeOfDay;
	}

	public void setTimeOfDay(java.time.LocalTime timeOfDay) {
		this.timeOfDay = timeOfDay;
	}

	public java.lang.String getWeatherConditions() {
		return this.weatherConditions;
	}

	public void setWeatherConditions(java.lang.String weatherConditions) {
		this.weatherConditions = weatherConditions;
	}

	public java.util.List<com.property_insurance.car_accident_claim_process.PersonInvolved> getPersonInvolved() {
		return this.personInvolved;
	}

	public void setPersonInvolved(
			java.util.List<com.property_insurance.car_accident_claim_process.PersonInvolved> personInvolved) {
		this.personInvolved = personInvolved;
	}

	public java.util.List<com.property_insurance.car_accident_claim_process.PoliceOfficer> getPoliceOfficer() {
		return this.policeOfficer;
	}

	public void setPoliceOfficer(
			java.util.List<com.property_insurance.car_accident_claim_process.PoliceOfficer> policeOfficer) {
		this.policeOfficer = policeOfficer;
	}

	public java.time.OffsetDateTime getFilingDate() {
		return this.filingDate;
	}

	public void setFilingDate(java.time.OffsetDateTime filingDate) {
		this.filingDate = filingDate;
	}

	public java.time.OffsetDateTime getAccidentDate() {
		return this.accidentDate;
	}

	public void setAccidentDate(java.time.OffsetDateTime accidentDate) {
		this.accidentDate = accidentDate;
	}

	public Claim(
			java.math.BigInteger id,
			java.math.BigInteger memberId,
			java.lang.String location,
			java.time.LocalTime timeOfDay,
			java.lang.String weatherConditions,
			java.util.List<com.property_insurance.car_accident_claim_process.PersonInvolved> personInvolved,
			java.util.List<com.property_insurance.car_accident_claim_process.PoliceOfficer> policeOfficer,
			java.time.OffsetDateTime filingDate,
			java.time.OffsetDateTime accidentDate) {
		this.id = id;
		this.memberId = memberId;
		this.location = location;
		this.timeOfDay = timeOfDay;
		this.weatherConditions = weatherConditions;
		this.personInvolved = personInvolved;
		this.policeOfficer = policeOfficer;
		this.filingDate = filingDate;
		this.accidentDate = accidentDate;
	}

}