package com.property_insurance.car_accident_claim_process;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PersonInvolved implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PersonInvolved() {
    }




}