package com.property_insurance.car_accident_claim_process;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Policy")
public class Policy implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.math.BigInteger id;
	private String memberId;
	private java.lang.Integer timeLimit;
	private java.lang.Double deductible;
	private java.lang.Double transportationExpenseCoverage;
	private java.lang.Double oemPartsCoverage;
	private java.lang.Double carLiabilityCoverage;
	private java.lang.Double uninsuradeAndUnderinsuredMototistCoverage;
	private java.lang.Double comprehensiveCoverage;
	private java.lang.Double collisionCoverage;
	private java.lang.Double medicalPaymentsCoverage;
	private java.lang.Double personalInjuryProtection;

	public Policy() {
	}

	public java.math.BigInteger getId() {
		return this.id;
	}

	public void setId(java.math.BigInteger id) {
		this.id = id;
	}

	public java.lang.Integer getTimeLimit() {
		return this.timeLimit;
	}

	public void setTimeLimit(java.lang.Integer timeLimit) {
		this.timeLimit = timeLimit;
	}

	public java.lang.Double getDeductible() {
		return this.deductible;
	}

	public void setDeductible(java.lang.Double deductible) {
		this.deductible = deductible;
	}

	public java.lang.Double getTransportationExpenseCoverage() {
		return this.transportationExpenseCoverage;
	}

	public void setTransportationExpenseCoverage(
			java.lang.Double transportationExpenseCoverage) {
		this.transportationExpenseCoverage = transportationExpenseCoverage;
	}

	public java.lang.Double getOemPartsCoverage() {
		return this.oemPartsCoverage;
	}

	public void setOemPartsCoverage(java.lang.Double oemPartsCoverage) {
		this.oemPartsCoverage = oemPartsCoverage;
	}

	public java.lang.Double getCarLiabilityCoverage() {
		return this.carLiabilityCoverage;
	}

	public void setCarLiabilityCoverage(java.lang.Double carLiabilityCoverage) {
		this.carLiabilityCoverage = carLiabilityCoverage;
	}

	public java.lang.Double getUninsuradeAndUnderinsuredMototistCoverage() {
		return this.uninsuradeAndUnderinsuredMototistCoverage;
	}

	public void setUninsuradeAndUnderinsuredMototistCoverage(
			java.lang.Double uninsuradeAndUnderinsuredMototistCoverage) {
		this.uninsuradeAndUnderinsuredMototistCoverage = uninsuradeAndUnderinsuredMototistCoverage;
	}

	public java.lang.Double getComprehensiveCoverage() {
		return this.comprehensiveCoverage;
	}

	public void setComprehensiveCoverage(java.lang.Double comprehensiveCoverage) {
		this.comprehensiveCoverage = comprehensiveCoverage;
	}

	public java.lang.Double getCollisionCoverage() {
		return this.collisionCoverage;
	}

	public void setCollisionCoverage(java.lang.Double collisionCoverage) {
		this.collisionCoverage = collisionCoverage;
	}

	public java.lang.Double getMedicalPaymentsCoverage() {
		return this.medicalPaymentsCoverage;
	}

	public void setMedicalPaymentsCoverage(
			java.lang.Double medicalPaymentsCoverage) {
		this.medicalPaymentsCoverage = medicalPaymentsCoverage;
	}

	public java.lang.Double getPersonalInjuryProtection() {
		return this.personalInjuryProtection;
	}

	public void setPersonalInjuryProtection(
			java.lang.Double personalInjuryProtection) {
		this.personalInjuryProtection = personalInjuryProtection;
	}

	public java.lang.String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(java.lang.String memberId) {
		this.memberId = memberId;
	}

	public Policy(java.math.BigInteger id, java.lang.String memberId,
			java.lang.Integer timeLimit, java.lang.Double deductible,
			java.lang.Double transportationExpenseCoverage,
			java.lang.Double oemPartsCoverage,
			java.lang.Double carLiabilityCoverage,
			java.lang.Double uninsuradeAndUnderinsuredMototistCoverage,
			java.lang.Double comprehensiveCoverage,
			java.lang.Double collisionCoverage,
			java.lang.Double medicalPaymentsCoverage,
			java.lang.Double personalInjuryProtection) {
		this.id = id;
		this.memberId = memberId;
		this.timeLimit = timeLimit;
		this.deductible = deductible;
		this.transportationExpenseCoverage = transportationExpenseCoverage;
		this.oemPartsCoverage = oemPartsCoverage;
		this.carLiabilityCoverage = carLiabilityCoverage;
		this.uninsuradeAndUnderinsuredMototistCoverage = uninsuradeAndUnderinsuredMototistCoverage;
		this.comprehensiveCoverage = comprehensiveCoverage;
		this.collisionCoverage = collisionCoverage;
		this.medicalPaymentsCoverage = medicalPaymentsCoverage;
		this.personalInjuryProtection = personalInjuryProtection;
	}

}